# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-09 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colombiaDecide', '0002_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotosConsulta',
            fields=[
                ('id_votos', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
                ('total_si', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'votos_consulta',
                'managed': False,
            },
        ),
    ]
